# Sources:
# - https://bookdown.org/yihui/bookdown/github.html
# - https://bookdown.org/yihui/bookdown/build-the-book.html#build-the-book

language: r
r: bioc-devel
os: linux
cache: packages
pandoc_version: 1.19.2.1

warnings_are_errors: false

env:
  - R_REMOTES_UPGRADE="always"

r_packages:
  - BiocManager

before_install:
  - mkdir -p ~/.R
  - echo -e 'MAKEFLAGS = -j2' > ~/.R/Makevars
  - echo 'options(Ncpus = 2)' > ~/.Rprofile
  - Rscript -e 'install.packages("devtools")'
  - Rscript -e 'devtools::install(dependencies=TRUE)'
  - Rscript -e 'BiocManager::install("Rtsne")'

r_build_args: "--no-manual --no-resave-data"
r_check_args: "--no-build-vignettes --no-manual --timings"

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
